# Generated by Django 6.0.7 on 2026-07-20 07:59

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=300)),
                ('bio', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Bio')),
                ('avatar', models.ImageField(blank=True, upload_to='profile/')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('resume', models.FileField(blank=True, upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
